### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/nas-hdd/shoubin/pretrained_model/hub/checkpoints/qformer_loc.pth

### ISSUE THREAD

**Issue by ontheway-arch** [Yui010206/SeViLA#11]
![image](https://github.com/Yui010206/SeViLA/assets/56793829/2e8127e7-0dd8-48b6-80cc-218c35c24af7)

**Comment by msra-jqxu** [comment]
@ontheway-arch Hi, may I ask how did you solve this problem? I met the same problem here.

**Comment by Yui010206** [comment]
> @ontheway-arch Hi, may I ask how did you solve this problem? I met the same problem here.

Hi,  we uploaded ckpt [here](https://drive.google.com/file/d/13hE_BQDflkzYrHVmVGddRSt8VMa0ouGB/view) (also feel free to check readme)
please download the ckpt and replace this path with your path. Thanks!

**Comment by msra-jqxu** [comment]
@Yui010206  Thanks very much!
