### ISSUE TITLE
How to load the parameters of vit and t5?

### ISSUE THREAD

**Issue by zhl98** [Yui010206/SeViLA#12]
Hello.
I see that the script uses the following command to load the model, but there are no parameters for vit and t5 in it. How can I load them?

`load_finetuned: True
  finetuned: 'https://huggingface.co/Shoubin/SeViLA/resolve/main/sevila_pretrained.pth'`

![image](https://github.com/Yui010206/SeViLA/assets/51871747/9e6bf8e2-a8cf-4798-8080-7284c3319035)

**Comment by Domogro** [comment]
I have the same issue, how did you do it?

**Comment by Yui010206** [comment]
Hi, thanks for your interest SeViLA project. please check this [issue](https://github.com/Yui010206/SeViLA/issues/17) for details.
