### ISSUE TITLE
Can you provide the file qformer_loc.pth？

### ISSUE THREAD

**Issue by ontheway-arch** [Yui010206/SeViLA#15]
When I run the pre-train code 'sh run_scripts/sevila/pre-train/pretrain_qvh.sh', it told me the file qformer_loc.pth not find.
The error is in blip2.py 
![image](https://github.com/Yui010206/SeViLA/assets/56793829/41b4967e-7bac-4865-af8a-508613f50943)

**Comment by Yui010206** [comment]
Thanks for your interest in our work, we have updated ReadME and uploaded [qformer_loc.pth](https://drive.google.com/file/d/13hE_BQDflkzYrHVmVGddRSt8VMa0ouGB/view).
