### ISSUE TITLE
Problems encountered when running the inference script

### ISSUE THREAD

**Issue by isTTTu** [Yui010206/SeViLA#16]
Hi，when I run the inference code :sh run_scripts/sevila/inference/nextqa_infer.sh, I've been encountering the following problem all along. Could you help me solve it?（This is the first time I came into contact with  multimodal large model, I didn't really understand it）
<img width="663" alt="1692583235718" src="https://github.com/Yui010206/SeViLA/assets/89306505/8aa80941-bea9-4ca2-95dc-a3ab09af5418">
<img width="665" alt="1692583320164" src="https://github.com/Yui010206/SeViLA/assets/89306505/1f557f74-cbfa-4d46-a35f-7ab513e7b7bf">

The script used is : 

# parameters/data path
result_dir="/home/txz/Result/"
train_path="/home/txz/SeViLA/sevila_datasets/nextqa/train.json"
val_path="/home/txz/SeViLA/sevila_datasets/nextqa/val.json"
video_path="/home/txz/SeViLA/video_feats/nextqa/app_mot_train.h5"

exp_name='nextqa_infer'
ckpt='/home/txz/SeViLA/sevila_checkpoints/sevila_pretrained.pth'
CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.run --nproc_per_node=1 evaluate.py \
#CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.run --nproc_per_node=1 evaluate.py \
--config lavis/projects/sevila/eval/nextqa_eval.yaml \
--options run.output_dir=${result_dir}${exp_name} \
datasets.nextqa.build_info.annotations.train.storage=${train_path} \
datasets.nextqa.build_info.annotations.val.storage=${val_path} \
datasets.nextqa.build_info.annotations.test.storage=${val_path} \
datasets.nextqa.build_info.videos.storage=${video_path} \
model.frame_num=4 \
datasets.nextqa.vis_processor.eval.n_frms=32 \
run.batch_size_eval=8 \
model.task='qvh_freeze_loc_freeze_qa_vid' \
model.finetuned=${ckpt} \
run.task='videoqa'

In addition, the GPU I used is double RTX 2080Ti. I would also like to confirm what I should download？Is it the original video, the video frames and the video features provided by the data researcher or other features for video data?

**Comment by kuhne12** [comment]
It seems that you provided the wrong script parameter. In line 11 of the **nextqa_infer.sh** file, you should provide the parameter **"--cfg-path"** instead of **"-config"**. Hope this can help you.
