### ISSUE TITLE
The warning of missing keys

### ISSUE THREAD

**Issue by ontheway-arch** [Yui010206/SeViLA#17]
When I finetune Answers on my datasets,I find the warning of missing keys, how to find this keys
![image](https://github.com/Yui010206/SeViLA/assets/56793829/9afe4e42-09b3-4d07-b9dd-775cc827f814)

**Comment by Franklee95** [comment]
<img width="934" alt="image" src="https://github.com/Yui010206/SeViLA/assets/41943056/9a855997-2310-4547-ab44-6aa8a0a6ccde">
all missing keys are initialized correctly in this part

**Comment by ontheway-arch** [comment]
thanks for your answer.
