### ISSUE TITLE
About Localizer

### ISSUE THREAD

**Issue by PolarisHsu** [Yui010206/SeViLA#21]
Hello, Thank you for your great work! 
Does the Localizer+ in your paper refer to the one that has been pre-trained by QVHighlights but not fine-tuned on the QA data set? That is the sevila_pretrained.pth you provided?

**Comment by Yui010206** [comment]
Hi, thanks for your interest in our project. Yes, Localizer+ refers to the one that has been pre-trained by QVHighlights but not fine-tuned on the QA dataset.
