### ISSUE TITLE
HF Spaces demo not working ?

### ISSUE THREAD

**Issue by jena-shreyas** [Yui010206/SeViLA#22]
Hi, I've been trying to use the demo for inference on some examples. The demo loads properly, and I'm able to add videos to the demo but the inference always returns an Error. I even tried out each of the default examples provided on the website but the same issue persists. I've attached a sample screenshot of the problem :

![Screenshot from 2023-10-24 09-22-25](https://github.com/Yui010206/SeViLA/assets/85274016/0ef124f5-5e12-43d7-91f3-01103da83c3e)

Could you please help me out on this? Thanks in advance!

**Comment by Yui010206** [comment]
Hi, thanks for your interest in our project. We have fixed the HF demo bug, you may try it again.

**Comment by akshat-khare** [comment]
Hi, HF demo isnt working.
<img width="1552" alt="Screenshot 2023-12-16 at 12 39 26 PM" src="https://github.com/Yui010206/SeViLA/assets/25928898/e8b87cf3-a913-4c78-9ab6-ae17902ca21b">
