### ISSUE TITLE
HF Spaces demo not working.

### ISSUE THREAD

**Issue by akshat-khare** [Yui010206/SeViLA#26]
Huggingface demo not working
<img width="1552" alt="Screenshot 2023-12-16 at 12 40 56 PM" src="https://github.com/Yui010206/SeViLA/assets/25928898/00e0f8a1-5a7a-4210-aac4-8020b187cffd">

**Comment by Yui010206** [comment]
Hi, thanks for your interest in the SeViLA project. We have re-launched the demo page, and you may try it again.
