### ISSUE TITLE
Fine-tuned model checkpoints

### ISSUE THREAD

**Issue by tyleryzhu** [Yui010206/SeViLA#27]
Great work and code release! I was wondering if you could release the model checkpoints that the fine-tuning results in Table 1 were achieved with? This would help re-producibility of the work, thanks!

**Comment by Yui010206** [comment]
Hi, thanks for your interest in the SeViLA project. Unfortunately, we deleted some fine-tuned ckpt due to the limited storage. 
But we will try to re-train and release the fine-tuned ckpt soon. Thanks!
