### ISSUE TITLE
Could you please provide a sample to show annotation files after processing?

### ISSUE THREAD

**Issue by aixiaodewugege** [Yui010206/SeViLA#5]
Hi, I want to finetune your model on my dataset. But I am not clear about the structure of the annotation files and video files I should create.

Could you please help me?

**Comment by Yui010206** [comment]
Sure, here is a data example of annotation files:
`{"video": "1104/3555755537", "num_option": 5, "qid": "CW_3555755537_1", "a0": "follow woman.", "a1": "cleasn environment.", "a2": "resting.", "a3": "hot indoor.", "a4": "sunbathing in beach.", "answer": "2", "question": "why does the person lie down without wearing her footwear?"}`
We adopt a list of dictionaries and save them as a json file.
And feel free to check our [dataset](https://github.com/Yui010206/SeViLA/tree/main/sevila_data) page for more details.
